-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- name "End-4"

-- credit https://github.com/end-4/dots-hyprland

hl.config({
    animations = {
        enabled = true,

        {
            name = "windows",
            duration = 1,
            speed = 5,
            bezier = "default",
            style = "slide",
        },

        {
            name = "windowsIn",
            duration = 1,
            speed = 5,
            bezier = "default",
            style = "slide",
        },

        {
            name = "windowsOut",
            duration = 1,
            speed = 5,
            bezier = "default",
            style = "slide",
        },
    }
})
