-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- name "End-4"

-- credit https://github.com/end-4/dots-hyprland

hl.config({
    animations = {
        enabled = true,
        -- Animation curves
        -- use with .2s duration
        -- Animation configs
        -- animation = layers, 1, 2, md3_decel, slide
        -- animation = workspaces, 1, 2.5, softAcDecel, slide
        -- animation = workspaces, 1, 7, menu_decel, slidefade 15%
        -- animation = specialWorkspace, 1, 3, md3_decel, slidefadevert 15%
    },
})
