# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

windowrule = tile on, match:title ^(Microsoft-edge)$
windowrule = tile on, match:title ^(Brave-browser)$
windowrule = tile on, match:title ^(Chromium)$
windowrule = float on, match:title ^(pavucontrol)$
windowrule = float on, match:title ^(blueman-manager)$
windowrule = float on, match:title ^(nm-connection-editor)$
windowrule = float on, match:title ^(qalculate-gtk)$

# Gnome Calendar
windowrule = float on, match:title ^(Calendar)$
windowrule = move 1220 295, match:title ^(Calendar)$
windowrule = size 100 100, match:title ^(Calendar)$
windowrule = pin on, match:title ^(Calendar)$
# windowrule = no_border on, match:title ^(Calendar)$
windowrule = no_blur on, match:title ^(Calendar)$

# Gnome Calculator
windowrule = float on, match:title ^(Calculator)$
windowrule = move 2315 1070, match:title ^(Calculator)$
windowrule = size 100 100, match:title ^(Calculator)$
windowrule = pin on, match:title ^(Calculator)$

# Browser Picture in Picture
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = size 640 360, match:title ^(Picture-in-Picture)$
windowrule = pin on, match:title ^(Picture-in-Picture)$
windowrule = move 74% 74%, match:title ^(Picture-in-Picture)$

# idleinhibit
windowrule = idle_inhibit fullscreen, match:class ([window]) # Available modes: none, always, focus, fullscreen

#xwayland related rules
# when moving objects in resolve a large border is produced 
# This rule prevents that and serves as a template for any problematic xwayland apps
windowrule = no_blur on, match:class ^(\bresolve\b)$, match:xwayland 1
# This is a general rule for xwayland apps but can have other consequences 
# for one user it impacted EMACs so it's disabled by default 
# It's here as a reference or for quick triage of xwayland ap
#windowrule = no_blur, xwayland:1

