---
user: mj
domain: home.lab
dns:
  - 192.168.1.4
  - 1.1.1.1
git_dir: "/home/{{ user }}/github"

allow_sudo:
  - /bin/kill
  - /usr/bin/dnf
  - /usr/bin/ps
  - /usr/bin/systemctl
  - /usr/bin/mount
  - /usr/bin/sshfs
  - /usr/bin/docker

dotfiles:
  - src: "{{ git_dir }}/fedora_desktop_sysprep/dotfiles/.vimrc"
    dest: "/home/{{ user }}/.vimrc"
  - src: "{{ git_dir }}/fedora_desktop_sysprep/dotfiles/.p10k-8color.zsh"
    dest: "/home/{{ user }}/.p10k-8color.zsh"
  - src: "{{ git_dir }}/fedora_desktop_sysprep/dotfiles/.p10k.zsh"
    dest: "/home/{{ user }}/.p10k.zsh"
  - src: "{{ git_dir }}/fedora_desktop_sysprep/dotfiles/.alias.zsh"
    dest: /home/{{ user }}/.alias.zsh
  - src: "{{ git_dir }}/fedora_desktop_sysprep/dotfiles/.zshenv"
    dest: "/home/{{ user }}/.zshenv"
  - src: "{{ git_dir }}/fedora_desktop_sysprep/dotfiles/.zshrc"
    dest: "/home/{{ user }}/.zshrc"

symlinks:
  - src: "/home/{{ user }}/.vimrc"
    dest: /root/.vimrc
  - src: "/home/{{ user }}/.vim"
    dest: /root/.vim
  - src: "/home/{{ user }}/.p10k.zsh"
    dest: /root/.p10k.zsh
  - src: "/home/{{ user }}/.alias.zsh"
    dest: /root/.alias.zsh
  - src: "/home/{{ user }}/.zshenv"
    dest: /root/.zshenv
  - src: "/home/{{ user }}/.zshrc"
    dest: /root/.zshrc
  - src: "{{ git_dir }}/argos/argos@pew.worldwidemann.com"
    dest: "/home/{{ user }}/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com"
  - src: "{{ git_dir }}/argos_extensions"
    dest: "/home/{{ user }}/.config/argos"

services:
  - name: docker
    state: started
    enabled: true
  - name: systemd-networkd
    state: stopped
    enabled: false
  - name: dnsmasq
    state: started
    enabled: true
  - name: sshd
    state: started
    enabled: true

enable_repositories:
  - name: webapp-manager
    desc: Copr repo for webapp-manager owned by refi64
    url: https://download.copr.fedorainfracloud.org/results/refi64/webapp-manager/fedora-$releasever-$basearch/
    gpgkey: https://download.copr.fedorainfracloud.org/results/refi64/webapp-manager/pubkey.gpg
  - name: docker-ce-stable
    desc: Docker CE Stable - $basearch
    url: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/fedora/gpg
  - name: google-cloud-cli
    desc: Google Cloud CLI
    url: https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  - name: hashicorp
    desc: Hashicorp Stable - $basearch
    url: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    gpgkey: https://rpm.releases.hashicorp.com/gpg
  - name: insync
    desc: insync repo
    url: http://yum.insync.io/fedora/$releasever/
    gpgkey: https://d2t3ff60b2tol4.cloudfront.net/repomd.xml.key
  - name: k8slens
    desc: Lens
    url: https://downloads.k8slens.dev/rpm/packages
    gpgkey: https://downloads.k8slens.dev/keys/gpg
  - name: nordvpn
    desc: NordVPN YUM repository - $basearch
    url: https://repo.nordvpn.com/yum/nordvpn/centos/$basearch
    gpgkey: https://repo.nordvpn.com/gpg/nordvpn_public.asc
  - name: rpmfusion-free
    desc: RPM Fusion for Fedora $releasever - Free
    url: http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/$basearch/os/
    gpgkey: https://download1.rpmfusion.org/free/fedora/RPM-GPG-KEY-rpmfusion-free-fedora-2020
  - name: rpmfusion-free-updates
    desc: RPM Fusion for Fedora $releasever - Free - Updates
    url: http://download1.rpmfusion.org/free/fedora/updates/$releasever/$basearch/
    gpgkey: https://download1.rpmfusion.org/free/fedora/RPM-GPG-KEY-rpmfusion-free-fedora-2020
  - name: kubernetes
    desc: Kubernetes
    url: https://pkgs.k8s.io/core:/stable:/v1.28/rpm/
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key

disable_repositories:
  - name: "copr:copr.fedorainfracloud.org:phracek:PyCharm"
    desc: Copr repo for PyCharm owned by phracek
    file: "_copr:copr.fedorainfracloud.org:phracek:PyCharm"
    url: https://download.copr.fedorainfracloud.org/results/phracek/PyCharm/fedora-$releasever-$basearch/
  - name: google-chrome
    desc: google-chrome
    file: google-chrome
    url: http://dl.google.com/linux/chrome/rpm/stable/x86_64
  - name: rpmfusion-nonfree-nvidia-driver
    desc: RPM Fusion for Fedora $releasever - Nonfree - NVIDIA Driver
    file: rpmfusion-nonfree-nvidia-driver
    url: http://download1.rpmfusion.org/nonfree/fedora/nvidia-driver/$releasever/$basearch/
  - name: rpmfusion-nonfree-steam
    desc: RPM Fusion for Fedora $releasever - Nonfree - Steam
    file: rpmfusion-nonfree-steam
    url: http://download1.rpmfusion.org/nonfree/fedora/steam/$releasever/$basearch/

bloat:
  - cheese
  - nvidia-gpu-firmware
  - totem
  - simple-scan
  - gedit
  - gnome-boxes
  - gnome-help
  - gnome-contacts
  - gnome-tour
  - gnome-photos
  - gnome-maps
  - gnome-characters
  - gnome-connections
  - gnome-system-monitor
  - gnome-terminal
  - libreoffice-calc
  - libreoffice-core
  - libreoffice-data
  - libreoffice-emailmerge
  - libreoffice-filters
  - libreoffice-graphicfilter
  - libreoffice-gtk3
  - libreoffice-gtk4
  - libreoffice-help-en
  - libreoffice-impress
  - libreoffice-langpack-en
  - libreoffice-ogltrans
  - libreoffice-opensymbol-fonts
  - libreoffice-pdfimport
  - libreoffice-pyuno
  - libreoffice-ure
  - libreoffice-ure-common
  - libreoffice-writer
  - libreoffice-x11
  - libreoffice-xsltfilter
