---
user: mj
domain: home.lab
dns:
  - 192.168.1.40
git_dir: "/home/{{ user }}/github"

allow_sudo:
  - /bin/kill
  - /usr/bin/dnf
  - /usr/bin/ps
  - /usr/bin/systemctl
  - /usr/bin/mount
  - /usr/bin/sshfs
  - /usr/bin/docker
  - /home/mj/.local/bin/fedora_update.sh

dotfiles:
  - src: "{{ git_dir }}/fedora_desktop_sysprep/dotfiles/.vimrc"
    dest: "/home/{{ user }}/.vimrc"
  - src: "{{ git_dir }}/fedora_desktop_sysprep/dotfiles/.p10k-8color.zsh"
    dest: "/home/{{ user }}/.p10k-8color.zsh"
  - src: "{{ git_dir }}/fedora_desktop_sysprep/dotfiles/.p10k.zsh"
    dest: "/home/{{ user }}/.p10k.zsh"
  - src: "{{ git_dir }}/fedora_desktop_sysprep/dotfiles/.alias.zsh"
    dest: /home/{{ user }}/.alias.zsh
  - src: "{{ git_dir }}/fedora_desktop_sysprep/dotfiles/.zshenv"
    dest: "/home/{{ user }}/.zshenv"
  - src: "{{ git_dir }}/fedora_desktop_sysprep/dotfiles/.zshrc"
    dest: "/home/{{ user }}/.zshrc"
  - src: "{{ git_dir }}/fedora_desktop_sysprep/dotfiles/.alacritty.toml"
    dest: "/home/{{ user }}/.alacritty.toml"

symlinks:
  - src: "/home/{{ user }}/.vimrc"
    dest: /root/.vimrc
  - src: "/home/{{ user }}/.vim"
    dest: /root/.vim
  - src: "/home/{{ user }}/.p10k.zsh"
    dest: /root/.p10k.zsh
  - src: "/home/{{ user }}/.alias.zsh"
    dest: /root/.alias.zsh
  - src: "/home/{{ user }}/.zshenv"
    dest: /root/.zshenv
  - src: "/home/{{ user }}/.zshrc"
    dest: /root/.zshrc
  - src: "{{ git_dir }}/argos/argos@pew.worldwidemann.com"
    dest: "/home/{{ user }}/.local/share/gnome-shell/extensions/argos@pew.worldwidemann.com"
  - src: "{{ git_dir }}/argos_extensions"
    dest: "/home/{{ user }}/.config/argos"

services:
  - name: docker
    state: started
    enabled: true
  - name: systemd-networkd
    state: stopped
    enabled: false
  - name: dnsmasq
    state: started
    enabled: true
  - name: sshd
    state: started
    enabled: true

enable_repositories:
  - name: docker-ce-stable
    desc: Docker CE Stable - $basearch
    url: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/fedora/gpg
  - name: insync
    desc: insync repo
    url: http://yum.insync.io/fedora/$releasever/
    gpgkey: https://d2t3ff60b2tol4.cloudfront.net/repomd.xml.key
  - name: rpmfusion-free
    desc: RPM Fusion for Fedora $releasever - Free
    url: http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/$basearch/os/
    gpgkey: https://download1.rpmfusion.org/free/fedora/RPM-GPG-KEY-rpmfusion-free-fedora-2020
  - name: rpmfusion-free-updates
    desc: RPM Fusion for Fedora $releasever - Free - Updates
    url: http://download1.rpmfusion.org/free/fedora/updates/$releasever/$basearch/
    gpgkey: https://download1.rpmfusion.org/free/fedora/RPM-GPG-KEY-rpmfusion-free-fedora-2020
  - name: kubernetes
    desc: Kubernetes
    url: https://pkgs.k8s.io/core:/stable:/v1.33/rpm/
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.33/rpm/repodata/repomd.xml.key
  - name: LACT
    desc: Copr repo for LACT owned by ilyaz
    url: https://download.copr.fedorainfracloud.org/results/ilyaz/LACT/fedora-$releasever-$basearch/
    gpgkey: https://download.copr.fedorainfracloud.org/results/ilyaz/LACT/pubkey.gpg

disable_repositories: []

fonts:
  - https://github.com/romkatv/powerlevel10k-media/raw/refs/heads/master/MesloLGS%20NF%20Regular.ttf
  - https://github.com/romkatv/powerlevel10k-media/raw/refs/heads/master/MesloLGS%20NF%20Bold.ttf
  - https://github.com/romkatv/powerlevel10k-media/raw/refs/heads/master/MesloLGS%20NF%20Italic.ttf
  - https://github.com/romkatv/powerlevel10k-media/raw/refs/heads/master/MesloLGS%20NF%20Bold%20Italic.ttf

bloat:
  - nvidia-gpu-firmware
  - totem
  - simple-scan
  - gnome-boxes
  - gnome-contacts
  - gnome-tour
  - gnome-maps
  - gnome-characters
  - gnome-connections
  - gnome-system-monitor
  - unoconv
  - libreoffice-calc
  - libreoffice-core
  - libreoffice-data
  - libreoffice-emailmerge
  - libreoffice-filters
  - libreoffice-graphicfilter
  - libreoffice-gtk3
  - libreoffice-gtk4
  - libreoffice-help-en
  - libreoffice-impress
  - libreoffice-langpack-en
  - libreoffice-ogltrans
  - libreoffice-opensymbol-fonts
  - libreoffice-pdfimport
  - libreoffice-pyuno
  - libreoffice-ure
  - libreoffice-ure-common
  - libreoffice-writer
  - libreoffice-xsltfilter

# Extensions IDs from https://extensions.gnome.org/
gnome_user: "{{ user }}"
gnome_extensions:
  - id: 16 # Auto Move Windows
    enable: true
  - id: 3991 # Bluetooth battery indicator
    enable: true
  - id: 3193 # Blur my Shell
    enable: false
  - id: 2917 # Bring Out Submenu Of Power Off Button
    enable: true
  - id: 4679 # Burn My Windows
    enable: true
  - id: 517 # Caffeine
    enable: false
  - id: 3396 # Color Picker
    enable: true
  - id: 1160 # Dash to Panel
    enable: true
  - id: 6358 # Disable workspace switcher overlay
    enable: true
  - id: 3088 # Extension List
    enable: false
  - id: 6406 # Fedora Linux Update Indicator
    enable: true
  - id: 4481 # Forge
    enable: true
  - id: 4158 # Gnome 4x UI Improvements
    enable: true
  - id: 2983 # IP Finder
    enable: false
  - id: 4099 # No overview at start-up
    enable: true
  - id: 1616 # panel scroll
    enable: true
  - id: 4691 # PiP on top
    enable: true
  - id: 4736 # Smart Auto Move
    enable: false
  - id: 19 # User Themes
    enable: true
