---
user: mj
domain: home.lab
dns:
  - 192.168.1.4
  - 1.1.1.1
git_dir: "/home/{{ user }}/github"

allow_sudo:
  - /bin/kill
  - /usr/bin/dnf
  - /usr/bin/ps
  - /usr/bin/systemctl
  - /usr/bin/mount
  - /usr/bin/sshfs
  - /usr/bin/docker

symlinks:
  - src: "/home/{{ user }}/.vimrc"
    dest: /root/.vimrc
  - src: "/home/{{ user }}/.vim"
    dest: /root/.vim
  - src: "/home/{{ user }}/.p10k.zsh"
    dest: /root/.p10k.zsh
  - src: "/home/{{ user }}/.alias.zsh"
    dest: /root/.alias.zsh
  - src: "/home/{{ user }}/.zshenv"
    dest: /root/.zshenv
  - src: "/home/{{ user }}/.zshrc"
    dest: /root/.zshrc

services:
  - name: docker
    state: started
    enabled: true
  - name: systemd-networkd
    state: stopped
    enabled: false
  - name: dnsmasq
    state: started
    enabled: true

cron_jobs:
  - name: Sync google photos
    job: '/home/{{ user }}/.local/bin/gphotos-sync /home/{{ user }}/google/photos/jankunasmartynas >> /var/log/gphotos-sync.log 2>&1'
  - name: Git backup
    job: 'cd {{ git_dir }}/fedora_desktop_sysprep && ./backup.sh'

git_repos:
  - repo: https://github.com/f5AFfMhv/fedora_desktop_sysprep.git
    dest: "{{ git_dir }}/fedora_desktop_sysprep"
  - repo: https://github.com/Coda-Coda/argos.git
    dest: "{{ git_dir }}/argos"
  - repo: https://github.com/gohugoio/hugo.git
    dest: "{{ git_dir }}/hugo"
  - repo: https://github.com/ventoy/ventoy.git
    dest: "{{ git_dir }}/ventoy"
  - repo: https://github.com/b3nj5m1n/xdg-ninja.git
    dest: "{{ git_dir }}/xdg-ninja"
  - repo: https://github.com/romkatv/zsh4humans.git
    dest: "{{ git_dir }}/zsh4humans"
  - repo: https://github.com/vinceliuice/Graphite-gtk-theme.git
    dest: "{{ git_dir }}/Graphite-gtk-theme"
  - repo: https://gitlab.com/VandalByte/darkmatter-grub-theme.git
    dest: "{{ git_dir }}/darkmatter-grub-theme"
  - repo: https://github.com/abertsch/Menlo-for-Powerline.git
    dest: "{{ git_dir }}/Menlo-for-Powerline"
  - repo: https://github.com/preservim/nerdtree.git
    dest: "{{ git_dir }}/nerdtree"
  - repo: https://github.com/sb-ocr/ocreeb-12.git
    dest: "{{ git_dir }}/ocreeb-12"
  - repo: https://github.com/refi64/stylepak.git
    dest: "{{ git_dir }}/stylepak"
  - repo: https://github.com/vinceliuice/Tela-circle-icon-theme.git
    dest: "{{ git_dir }}/Tela-circle-icon-theme"
  - repo: https://github.com/yilozt/rounded-window-corners.git
    dest: "{{ git_dir }}/rounded-window-corners"

enable_repositories:
  - name: webapp-manager
    desc: Copr repo for webapp-manager owned by refi64
    url: https://download.copr.fedorainfracloud.org/results/refi64/webapp-manager/fedora-$releasever-$basearch/
    gpgkey: https://download.copr.fedorainfracloud.org/results/refi64/webapp-manager/pubkey.gpg
  - name: docker-ce-stable
    desc: Docker CE Stable - $basearch
    url: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/fedora/gpg
  - name: google-cloud-cli
    desc: Google Cloud CLI
    url: https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  - name: hashicorp
    desc: Hashicorp Stable - $basearch
    url: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    gpgkey: https://rpm.releases.hashicorp.com/gpg
  - name: insync
    desc: insync repo
    url: http://yum.insync.io/fedora/$releasever/
    gpgkey: https://d2t3ff60b2tol4.cloudfront.net/repomd.xml.key
  - name: k8slens
    desc: Lens
    url: https://downloads.k8slens.dev/rpm/packages
    gpgkey: https://downloads.k8slens.dev/keys/gpg
  - name: nordvpn
    desc: NordVPN YUM repository - $basearch
    url: https://repo.nordvpn.com/yum/nordvpn/centos/$basearch
    gpgkey: https://repo.nordvpn.com/gpg/nordvpn_public.asc
  - name: rpmfusion-free
    desc: RPM Fusion for Fedora $releasever - Free
    url: http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/$basearch/os/
    gpgkey: https://download1.rpmfusion.org/free/fedora/RPM-GPG-KEY-rpmfusion-free-fedora-2020
  - name: rpmfusion-free-updates
    desc: RPM Fusion for Fedora $releasever - Free - Updates
    url: http://download1.rpmfusion.org/free/fedora/updates/$releasever/$basearch/
    gpgkey: https://download1.rpmfusion.org/free/fedora/RPM-GPG-KEY-rpmfusion-free-fedora-2020
  - name: kubernetes
    desc: Kubernetes
    url: https://pkgs.k8s.io/core:/stable:/v1.28/rpm/
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key

disable_repositories:
  - name: 'copr:copr.fedorainfracloud.org:phracek:PyCharm'
    desc: Copr repo for PyCharm owned by phracek
    file: '_copr:copr.fedorainfracloud.org:phracek:PyCharm'
    url: https://download.copr.fedorainfracloud.org/results/phracek/PyCharm/fedora-$releasever-$basearch/
  - name: google-chrome
    desc: google-chrome
    file: google-chrome
    url: http://dl.google.com/linux/chrome/rpm/stable/x86_64
  - name: rpmfusion-nonfree-nvidia-driver
    desc: RPM Fusion for Fedora $releasever - Nonfree - NVIDIA Driver
    file: rpmfusion-nonfree-nvidia-driver
    url: http://download1.rpmfusion.org/nonfree/fedora/nvidia-driver/$releasever/$basearch/
  - name: rpmfusion-nonfree-steam
    desc: RPM Fusion for Fedora $releasever - Nonfree - Steam
    file: rpmfusion-nonfree-steam
    url: http://download1.rpmfusion.org/nonfree/fedora/steam/$releasever/$basearch/

rpms:
  - ansible
  - ansible-collection-community-docker
  - ansible-core
  - asciinema
  - bat
  - chromium
  - containerd.io
  - cpu-x
  - dconf-editor
  - docker-ce
  - docker-compose-plugin
  - feh
  - fuse-sshfs
  - google-cloud-sdk
  - google-cloud-sdk-gke-gcloud-auth-plugin
  - htop
  - hugo
  - insync
  - iperf
  - jq
  - keepassxc
  - lens
  - lm_sensors
  - lsd
  - neofetch
  - net-tools
  - nfs-utils
  - nordvpn
  - python3-pip
  - ranger
  - solaar
  - telnet
  - terraform
  - thefuck
  - timeshift
  - powerline
  - vim
  - vim-powerline
  - powerline-fonts
  - vim-ansible
  - virt-manager
  - zsh
  - webapp-manager
  - libgda
  - libgda-sqlite
  - moreutils
  - ulauncher
  - xdotool
  - rpi-imager
  - crontabs
  - cups
  - lame-libs
  - gstreamer1
  - gstreamer1-plugin-libav
  - gstreamer1-plugin-openh264
  - gstreamer1-plugins-bad-free
  - gstreamer1-plugins-bad-free-extras
  - gstreamer1-plugins-bad-free-fluidsynth
  - gstreamer1-plugins-bad-free-wildmidi
  - gstreamer1-plugins-bad-free-zbar
  - gstreamer1-plugins-bad-freeworld
  - gstreamer1-plugins-base.i686
  - gstreamer1-plugins-base
  - gstreamer1-plugins-good.i686
  - gstreamer1-plugins-good
  - gstreamer1-plugins-good-extras
  - gstreamer1-plugins-good-gtk
  - gstreamer1-plugins-good-qt
  - gstreamer1-plugins-ugly-free
  - kubectl
  - gnome-tweaks
  - distrobox
  - clapper

bloat:
  - cheese
  - nvidia-gpu-firmware
  - totem
  - simple-scan
  - gedit
  - gnome-boxes
  - gnome-contacts
  - gnome-tour
  - gnome-photos
  - gnome-maps
  - gnome-characters
  - libreoffice-calc
  - libreoffice-core
  - libreoffice-data
  - libreoffice-emailmerge
  - libreoffice-filters
  - libreoffice-graphicfilter
  - libreoffice-gtk3
  - libreoffice-gtk4
  - libreoffice-help-en
  - libreoffice-impress
  - libreoffice-langpack-en
  - libreoffice-ogltrans
  - libreoffice-opensymbol-fonts
  - libreoffice-pdfimport
  - libreoffice-pyuno
  - libreoffice-ure
  - libreoffice-ure-common
  - libreoffice-writer
  - libreoffice-x11
  - libreoffice-xsltfilter

flatpaks:
  - cc.arduino.IDE2
  - com.getmailspring.Mailspring
  - com.github.tchx84.Flatseal
  - com.heroicgameslauncher.hgl
  - com.jgraph.drawio.desktop
  - com.raggesilver.BlackBox
  - com.spotify.Client
  - com.transmissionbt.Transmission
  - com.valvesoftware.Steam
  - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
  - io.github.hakandundar34coding.system-monitoring-center
  - io.github.jonmagon.kdiskmark
  - io.github.prateekmedia.appimagepool
  - io.github.realmazharhussain.GdmSettings
  - org.gnome.Extensions
  - org.kicad.KiCad
  - org.onlyoffice.desktopeditors
  - org.videolan.VLC
  - tv.plex.PlexDesktop
  - com.visualstudio.code
  - org.remmina.Remmina

python_packages:
  - autopep8
  - certifi
  - exif
  - Flask
  - google-auth
  - google-auth-oauthlib
  - gphotos-sync
  - jmespath
  - jsonschema
  - kubernetes
  - matplotlib
  - numpy
  - oauthlib
  - paramiko
  - PcbDraw
  - pcbnewTransition
  - Pinion
  - pipenv
  - virtualenv
  - virtualenv-clone
  - yamllint
  - youtube-dl
