---
user: mj
domain: home.lab
dns:
  - 192.168.1.40
home_dir: "/home/{{ user }}"
git_dir: "{{ home_dir }}/github"
dotfiles_dir: "{{ git_dir }}/fedora_desktop_sysprep/dotfiles"
sddm_theme: sddm-astronaut-theme
ml4w_flatpak_repo: https://mylinuxforwork.github.io/ml4w-flatpak-repo/ml4w-apps.flatpakrepo
ml4w_flatpak_gpg: https://mylinuxforwork.github.io/ml4w-flatpak-repo/ml4w-apps-public-key.asc

allow_sudo:
  - /bin/kill
  - /usr/bin/dnf
  - /usr/bin/ps
  - /usr/bin/systemctl
  - /usr/bin/mount
  - /usr/bin/sshfs
  - /usr/bin/docker

font_dirs:
  - "{{ git_dir }}/sddm-astronaut-theme/Fonts"
  - "{{ git_dir }}/p10k-media"
  - "{{ git_dir }}/ml4w/setup/fonts"

dotfiles:
  - vimrc
  - p10k.zsh
  - alias.zsh
  - zshrc
  - zshenv
  - alacritty.toml
  - gtkrc-2.0
  - gtk-3.0
  - gtk-4.0
  - hypr
  - ml4w
  - nwg-dock-hyprland
  - qt6ct
  - rofi
  - sidepad
  - swaync
  - waybar
  - waypaper
  - wlogout
  - xsettingsd
  - fastfetch

dotfile_symlinks:
  - vimrc
  - p10k.zsh
  - alias.zsh
  - zshrc
  - zshenv
  - alacritty.toml
  - gtkrc-2.0

services:
  - name: docker
    state: started
    enabled: true
  - name: systemd-networkd
    state: stopped
    enabled: false
  - name: dnsmasq
    state: started
    enabled: true
  - name: sshd
    state: started
    enabled: true

rpm_repositories:
  - name: docker-ce-stable
    desc: Docker CE Stable - $basearch
    url: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/fedora/gpg
  - name: insync
    desc: insync repo
    url: http://yum.insync.io/fedora/$releasever/
    gpgkey: https://d2t3ff60b2tol4.cloudfront.net/repomd.xml.key
  - name: copr.solopasha.hyprland
    desc: Hyprland and related packages
    url: https://download.copr.fedorainfracloud.org/results/solopasha/hyprland/fedora-$releasever-$basearch/
    gpgkey: https://download.copr.fedorainfracloud.org/results/solopasha/hyprland/pubkey.gpg
  - name: copr.erikreider.SwayNotificationCenter
    desc: SwayNotificationCenter and related packages
    url: https://download.copr.fedorainfracloud.org/results/erikreider/SwayNotificationCenter/fedora-$releasever-$basearch/
    gpgkey: https://download.copr.fedorainfracloud.org/results/erikreider/SwayNotificationCenter/pubkey.gpg

flatpak_repositories:
  - name: flathub
    url: "https://dl.flathub.org/repo/flathub.flatpakrepo"

python_packages:
  - hyprshade
  - screeninfo
  - ansible

binaries:
  - name: minikube
    url: https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
  - name: kubectl
    url: https://dl.k8s.io/release/v1.34.0/bin/linux/amd64/kubectl

rpms:
  # Development tools
  - python3-pip
  - python3-devel
  - python3-autopep8
  - python3-toml
  - python3-pyyaml
  - python3-wheel
  - python3-gobject
  - python3-ansible-lint
  - qt6ct
  - qt5-qtwayland
  - qt6-qtwayland
  - qt6-qtsvg
  - qt6-qtmultimedia
  - gcc
  - jq
  - yamllint
  - ansible
  - ansible-core
  - ansible-collection-community-docker
  - docker-ce
  - docker-compose-plugin
  - figlet
  - gum
  # Networking
  - openssl
  - nm-connection-editor
  - network-manager-applet
  - NetworkManager-tui
  - net-tools
  - telnet
  - iperf
  # System tools
  - zsh
  - crontabs
  - moreutils
  - lm_sensors
  - nfs-utils
  - openssh-askpass
  - fuse
  - fuse-sshfs
  - cups
  - flatpak
  - sddm
  - blueman
  - ImageMagick
  - inotify-tools
  - pavucontrol
  - gvfs
  - fastfetch
  # Libraries
  - lame-libs
  - libgda
  - libgda-sqlite
  - libnotify
  # Wayland + Hyprland + ML4W
  - hyprland
  - hyprpaper
  - hyprlock
  - hypridle
  - hyprpicker
  - xdg-user-dirs
  - xdg-desktop-portal-gtk
  - xdg-desktop-portal-hyprland
  - wlogout
  - waypaper
  - waybar
  - rofi-wayland
  - nwg-dock-hyprland
  - nwg-look
  - SwayNotificationCenter
  - xclip
  - brightnessctl
  - tumbler
  - slurp
  - cliphist
  - grim
  - uwsm
  - papirus-icon-theme
  - papirus-icon-theme-dark
  - dejavu-fonts-all
  - fontawesome-fonts
  - google-noto-emoji-fonts
  - google-noto-sans-cjk-fonts
    # Terminal tools
  - vim
  - vim-ansible
  - vim-powerline
  - powerline
  - powerline-fonts
  - lsd # LSDeluxe, a modern replacement for 'ls'
  - bat # Better cat
  - htop
  - radeontop
  - zoxide # Fast directory jumper
  - git
  - fzf # Fuzzy finder
  - rsync
  - unzip
  - wget
  - curl
  # GUI apps
  - virt-manager
  - insync # Google Drive client
  - solaar # Logitech device manager
  - rpi-imager
  - cpu-x
  - alacritty
  - vlc
  - nextcloud-client
  - gnome-calculator
  - gnome-software
  - gnome-text-editor
  - gnome-calendar
  - gnome-font-viewer
  - nautilus # File manager
  - evince # Document viewer
  - baobab # Disk Usage Analyzer
  - mediawriter # Fedora Media Writer
  - loupe # Image viewer
  - snapshot # Camera viewer

uninstall_rpms:
  - nvidia-gpu-firmware
  - totem
  - unoconv
  - libreoffice-calc
  - libreoffice-core
  - libreoffice-data
  - libreoffice-emailmerge
  - libreoffice-filters
  - libreoffice-graphicfilter
  - libreoffice-gtk3
  - libreoffice-gtk4
  - libreoffice-help-en
  - libreoffice-impress
  - libreoffice-langpack-en
  - libreoffice-ogltrans
  - libreoffice-opensymbol-fonts
  - libreoffice-pdfimport
  - libreoffice-pyuno
  - libreoffice-ure
  - libreoffice-ure-common
  - libreoffice-writer
  - libreoffice-xsltfilter
  - foot
  - Thunar
  - thunar-archive-plugin
  - firefox
  - kitty
  - yt-dlp
