---
cron_jobs:
  - name: Test job
    job: "echo test"

cron_env:
  - var: dummy
    val: var

git_repos:
  - repo: https://github.com/f5AFfMhv/fedora_desktop_sysprep.git
    dest: "{{ git_dir }}/fedora_desktop_sysprep"
  - repo: https://github.com/mylinuxforwork/dotfiles.git
    dest: "{{ git_dir }}/ml4w"
  - repo: https://github.com/Keyitdev/sddm-astronaut-theme.git
    dest: "{{ git_dir }}/{{ sddm_theme }}"
  - repo: https://github.com/romkatv/powerlevel10k-media.git
    dest: "{{ git_dir }}/p10k-media"

flatpaks:
  - com.github.tchx84.Flatseal
  - org.onlyoffice.desktopeditors
  - io.github.zen_browser.zen
  - ca.edestcroix.Recordbox
  - com.github.maoschanz.drawing
  - io.missioncenter.MissionCenter
  - io.github.flattool.Ignition # Startup app manager
  - io.github.amit9838.mousam # Weather app
