---
cron_jobs:
  - name: Sync google photos
    job: "$BASE_DIR/gphotos_sync.sh"
  - name: Timeshift backup verification
    job: "$BASE_DIR/timeshift_backup_verify.sh"
  - name: Git backup
    job: "#cd {{ git_dir }}/fedora_desktop_sysprep && ./backup.sh"
  - name: Note sync
    job: "cd /home/{{ user }}/Documents/Others/Notes/Notes && ./sync_notes.sh"

cron_env:
  - var: BASE_DIR
    val: /home/mj/google/drive/jankunasmartynas/Programming/scripts
  - var: HC_GPHOTOS
    val: 74e5d015-6d9c-4b63-8912-5f70491aff55
  - var: HC_FEDORA
    val: 8f2ded5b-8697-4899-8b68-759f7c46745f
  - var: HC_TIMESHIFT
    val: a346a6d0-6203-4520-b8f2-343da27a37bf

git_repos:
  - repo: git@github.com:f5AFfMhv/fedora_desktop_sysprep.git
    dest: "{{ git_dir }}/fedora_desktop_sysprep"
  - repo: git@github.com:f5AFfMhv/argos_extensions.git
    dest: "{{ git_dir }}/argos_extensions"
  - repo: git@github.com:f5AFfMhv/my-kicad-libraries.git
    dest: "{{ git_dir }}/my-kicad-libraries"
  - repo: https://github.com/p-e-w/argos.git
    dest: "{{ git_dir }}/argos"
  - repo: https://github.com/gohugoio/hugo.git
    dest: "{{ git_dir }}/hugo"
  - repo: https://github.com/b3nj5m1n/xdg-ninja.git
    dest: "{{ git_dir }}/xdg-ninja"
  - repo: https://github.com/romkatv/zsh4humans.git
    dest: "{{ git_dir }}/zsh4humans"
  - repo: https://github.com/vinceliuice/Graphite-gtk-theme.git
    dest: "{{ git_dir }}/Graphite-gtk-theme"
  - repo: https://gitlab.com/VandalByte/darkmatter-grub-theme.git
    dest: "{{ git_dir }}/darkmatter-grub-theme"
  - repo: https://github.com/abertsch/Menlo-for-Powerline.git
    dest: "{{ git_dir }}/Menlo-for-Powerline"
  - repo: https://github.com/preservim/nerdtree.git
    dest: "{{ git_dir }}/nerdtree"
  - repo: https://github.com/sb-ocr/ocreeb-12.git
    dest: "{{ git_dir }}/ocreeb-12"
  - repo: https://github.com/refi64/stylepak.git
    dest: "{{ git_dir }}/stylepak"
  - repo: https://github.com/vinceliuice/Tela-circle-icon-theme.git
    dest: "{{ git_dir }}/Tela-circle-icon-theme"
  - repo: https://github.com/yilozt/rounded-window-corners.git
    dest: "{{ git_dir }}/rounded-window-corners"
  - repo: https://github.com/comfyanonymous/ComfyUI.git
    dest: "{{ git_dir }}/ComfyUI"
  - repo: https://github.com/imarkoff/Marble-shell-theme.git
    dest: "{{ git_dir }}/Marble-shell-theme"
  - repo: https://github.com/vinceliuice/Fluent-gtk-theme.git
    dest: "{{ git_dir }}/Fluent-gtk-theme"

rpms:
  - python3.10
  - python3-pip
  - python3-devel
  - python3-autopep8
  - python3-certifi
  - python3-kubernetes
  - python3-jmespath
  - python3-jsonschema
  - python3-matplotlib
  - python3-oauthlib
  - python3-numpy
  - python3-paramiko
  - python3-flask
  - python3-pillow-devel
  - python3-toml
  - python3-pyyaml
  - python3-wheel
  - gstreamer1
  - gstreamer1-plugin-libav
  - gstreamer1-plugin-openh264
  - gstreamer1-plugins-bad-free
  - gstreamer1-plugins-bad-free-extras
  - gstreamer1-plugins-bad-free-fluidsynth
  - gstreamer1-plugins-bad-free-wildmidi
  - gstreamer1-plugins-bad-free-zbar
  - gstreamer1-plugins-bad-freeworld
  - gstreamer1-plugins-base.i686
  - gstreamer1-plugins-base
  - gstreamer1-plugins-good.i686
  - gstreamer1-plugins-good
  - gstreamer1-plugins-good-extras
  - gstreamer1-plugins-good-gtk
  - gstreamer1-plugins-good-qt
  - gstreamer1-plugins-ugly-free
  - gcc
  - openssl
  - crontabs
  - openssh-askpass
  - vim
  - vim-ansible
  - vim-powerline
  - powerline
  - powerline-fonts
  - cups
  - lame-libs
  - libgda
  - libgda-sqlite
  - moreutils
  - seahorse
  - dconf-editor
  - fuse-sshfs
  - net-tools
  - nfs-utils
  - lm_sensors
  - xdotool
  - yamllint
  - kubectl
  - terraform
  - ansible
  - ansible-core
  - ansible-collection-community-docker
  - docker-ce
  - docker-compose-plugin
  - google-cloud-cli
  - hugo
  - iperf
  - jq
  - lsd
  - bat
  - htop
  - zsh
  - telnet
  - distrobox
  - youtube-dl
  - nordvpn
  - neofetch
  - virt-manager
  - insync
  - keepassxc
  - lens
  - solaar
  - timeshift
  - webapp-manager
  - ulauncher
  - rpi-imager
  - gnome-tweaks
  - clapper
  - chromium
  - cpu-x
  - radeontop
  - ostree

flatpaks:
  - cc.arduino.IDE2
  - com.github.tchx84.Flatseal
  - com.heroicgameslauncher.hgl
  - com.jgraph.drawio.desktop
  - com.raggesilver.BlackBox
  - com.spotify.Client
  - com.valvesoftware.Steam
  - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
  - io.github.hakandundar34coding.system-monitoring-center
  - io.github.jonmagon.kdiskmark
  - io.github.prateekmedia.appimagepool
  - io.github.realmazharhussain.GdmSettings
  - com.mattjakeman.ExtensionManager
  - org.kicad.KiCad
  - org.onlyoffice.desktopeditors
  - org.videolan.VLC
  - com.visualstudio.code
  - io.github.giantpinkrobots.flatsweep
  - org.mozilla.Thunderbird
  - me.kozec.syncthingtk
  - com.github.iwalton3.jellyfin-media-player
  - md.obsidian.Obsidian
  - org.gimp.GIMP
  - io.github.flattool.Warehouse
  - io.github.zen_browser.zen

python_packages:
  - name: PcbDraw
    pip: pip3.12
  - name: pcbnewTransition
    pip: pip3.12
  - name: Pinion
    pip: pip3.12
  - name: thefuck
    pip: pip3.10
  - name: git+https://github.com/gilesknap/gphotos-sync.git
    pip: pip3.10
