---
cron_jobs:
  - name: Sync google photos
    job: "/home/{{ user }}/.local/bin/gphotos-sync /home/{{ user }}/google/photos/jankunasmartynas >> /var/log/gphotos-sync.log 2>&1"
  - name: Git backup
    job: "cd {{ git_dir }}/fedora_desktop_sysprep && ./backup.sh"

git_repos:
  - repo: git@github.com:f5AFfMhv/fedora_desktop_sysprep.git
    dest: "{{ git_dir }}/fedora_desktop_sysprep"
  - repo: git@github.com:f5AFfMhv/argos_extensions.git
    dest: "{{ git_dir }}/argos_extensions"
  - repo: hhttps://github.com/p-e-w/argos.git
    dest: "{{ git_dir }}/argos"
  - repo: https://github.com/gohugoio/hugo.git
    dest: "{{ git_dir }}/hugo"
  - repo: https://github.com/ventoy/ventoy.git
    dest: "{{ git_dir }}/ventoy"
  - repo: https://github.com/b3nj5m1n/xdg-ninja.git
    dest: "{{ git_dir }}/xdg-ninja"
  - repo: https://github.com/romkatv/zsh4humans.git
    dest: "{{ git_dir }}/zsh4humans"
  - repo: https://github.com/vinceliuice/Graphite-gtk-theme.git
    dest: "{{ git_dir }}/Graphite-gtk-theme"
  - repo: https://gitlab.com/VandalByte/darkmatter-grub-theme.git
    dest: "{{ git_dir }}/darkmatter-grub-theme"
  - repo: https://github.com/abertsch/Menlo-for-Powerline.git
    dest: "{{ git_dir }}/Menlo-for-Powerline"
  - repo: https://github.com/preservim/nerdtree.git
    dest: "{{ git_dir }}/nerdtree"
  - repo: https://github.com/sb-ocr/ocreeb-12.git
    dest: "{{ git_dir }}/ocreeb-12"
  - repo: https://github.com/refi64/stylepak.git
    dest: "{{ git_dir }}/stylepak"
  - repo: https://github.com/vinceliuice/Tela-circle-icon-theme.git
    dest: "{{ git_dir }}/Tela-circle-icon-theme"
  - repo: https://github.com/yilozt/rounded-window-corners.git
    dest: "{{ git_dir }}/rounded-window-corners"
  - repo: https://github.com/brunelli/gnome-shell-extension-installer.git
    dest: "{{ git_dir }}/gnome-shell-extension-installer"
  - repo: https://github.com/comfyanonymous/ComfyUI.git
    dest: "{{ git_dir }}/ComfyUI"

rpms:
  - python3.10
  - python3-pip
  - python3-devel
  - python3-autopep8
  - python3-certifi
  - python3-google-auth
  - python3-google-auth-oauthlib
  - python3-kubernetes
  - python3-jmespath
  - python3-jsonschema
  - python3-matplotlib
  - python3-oauthlib
  - python3-numpy
  - python3-paramiko
  - python3-flask
  - python3-pillow-devel
  - python3-toml
  - python3-pyyaml
  - python3-wheel
  - gstreamer1
  - gstreamer1-plugin-libav
  - gstreamer1-plugin-openh264
  - gstreamer1-plugins-bad-free
  - gstreamer1-plugins-bad-free-extras
  - gstreamer1-plugins-bad-free-fluidsynth
  - gstreamer1-plugins-bad-free-wildmidi
  - gstreamer1-plugins-bad-free-zbar
  - gstreamer1-plugins-bad-freeworld
  - gstreamer1-plugins-base.i686
  - gstreamer1-plugins-base
  - gstreamer1-plugins-good.i686
  - gstreamer1-plugins-good
  - gstreamer1-plugins-good-extras
  - gstreamer1-plugins-good-gtk
  - gstreamer1-plugins-good-qt
  - gstreamer1-plugins-ugly-free
  - gcc
  - openssl
  - crontabs
  - openssh-askpass
  - vim
  - vim-ansible
  - vim-powerline
  - powerline
  - powerline-fonts
  - cups
  - lame-libs
  - libgda
  - libgda-sqlite
  - moreutils
  - seahorse
  - dconf-editor
  - fuse-sshfs
  - net-tools
  - nfs-utils
  - lm_sensors
  - xdotool
  - yamllint
  - kubectl
  - terraform
  - ansible
  - ansible-core
  - ansible-collection-community-docker
  - docker-ce
  - docker-compose-plugin
  - google-cloud-sdk
  - google-cloud-sdk-gke-gcloud-auth-plugin
  - hugo
  - iperf
  - jq
  - lsd
  - bat
  - htop
  - zsh
  - telnet
  - distrobox
  - youtube-dl
  - nordvpn
  - neofetch
  - virt-manager
  - insync
  - keepassxc
  - lens
  - solaar
  - timeshift
  - webapp-manager
  - ulauncher
  - rpi-imager
  - gnome-tweaks
  - clapper
  - chromium
  - cpu-x
  - radeontop

flatpaks:
  - cc.arduino.IDE2
  - com.github.tchx84.Flatseal
  - com.heroicgameslauncher.hgl
  - com.jgraph.drawio.desktop
  - com.raggesilver.BlackBox
  - com.spotify.Client
  - com.transmissionbt.Transmission
  - com.valvesoftware.Steam
  - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
  - io.github.hakandundar34coding.system-monitoring-center
  - io.github.jonmagon.kdiskmark
  - io.github.prateekmedia.appimagepool
  - io.github.realmazharhussain.GdmSettings
  - com.mattjakeman.ExtensionManager
  - org.kicad.KiCad
  - org.onlyoffice.desktopeditors
  - org.videolan.VLC
  - tv.plex.PlexDesktop
  - com.visualstudio.code
  - org.remmina.Remmina
  - io.github.giantpinkrobots.flatsweep
  - org.mozilla.Thunderbird
  - net.cozic.joplin_desktop

python_packages:
  - name: PcbDraw
    pip: pip3.12
  - name: pcbnewTransition
    pip: pip3.12
  - name: Pinion
    pip: pip3.12
  - name: thefuck
    pip: pip3.10
  - name: git+https://github.com/gilesknap/gphotos-sync.git
    pip: pip3.10
