---
cron_jobs:
  - name: Git backup
    job: "#cd {{ git_dir }}/fedora_desktop_sysprep && ./backup.sh"
  - name: Note sync
    job: "#cd /home/{{ user }}/Documents/Others/Notes/Notes && ./sync_notes.sh"
  - name: SRV docker config sync
    job: "#/usr/bin/rsync -az mj@docker.home.lab:/opt/docker-compose/ /opt/docker-compose/ > /dev/null 2>&1"

cron_env:
  - var: BASE_DIR
    val: /home/mj/google/drive/jankunasmartynas/Programming/scripts
  - var: HC_FEDORA
    val: 8f2ded5b-8697-4899-8b68-759f7c46745f

git_repos:
  # - repo: git@github.com:f5AFfMhv/fedora_desktop_sysprep.git
  #   dest: "{{ git_dir }}/fedora_desktop_sysprep"
  - repo: https://github.com/romkatv/zsh4humans.git
    dest: "{{ git_dir }}/zsh4humans"
  - repo: https://github.com/abertsch/Menlo-for-Powerline.git
    dest: "{{ git_dir }}/Menlo-for-Powerline"
  - repo: https://github.com/sb-ocr/ocreeb-12.git
    dest: "{{ git_dir }}/ocreeb-12"
  - repo: https://github.com/comfyanonymous/ComfyUI.git
    dest: "{{ git_dir }}/ComfyUI"
  - repo: https://github.com/mylinuxforwork/dotfiles.git
    dest: "{{ git_dir }}/ml4w"
  - repo: https://github.com/Keyitdev/sddm-astronaut-theme.git
    dest: "{{ git_dir }}/{{ sddm_theme }}"
  - repo: https://github.com/romkatv/powerlevel10k-media.git
    dest: "{{ git_dir }}/p10k-media"

flatpaks:
  - cc.arduino.IDE2
  - com.github.tchx84.Flatseal
  - io.github.jonmagon.kdiskmark
  - org.kicad.KiCad
  - org.onlyoffice.desktopeditors
  - com.vscodium.codium
  - io.github.giantpinkrobots.flatsweep
  - org.mozilla.Thunderbird
  - me.kozec.syncthingtk
  - md.obsidian.Obsidian
  - io.github.flattool.Warehouse
  - io.github.zen_browser.zen
  - ca.edestcroix.Recordbox
  - com.github.maoschanz.drawing
  - io.github.ungoogled_software.ungoogled_chromium
  - io.missioncenter.MissionCenter
  - org.gnome.SoundRecorder
  - com.github.iwalton3.jellyfin-media-player
  - me.iepure.devtoolbox
  - org.sqlitebrowser.sqlitebrowser
  - io.github.flattool.Ignition
  - io.github.amit9838.mousam # Weather app
  - it.mijorus.gearlever # Appimage manager
  - io.github.plrigaux.sysd-manager # Systemd Manager

