-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- -----------------------------------------------------

-- Keyboard Layout

-- https://wiki.hyprland.org/Configuring/Variables/#input

-- -----------------------------------------------------

hl.config({
    input = {
        kb_layout = "us, lt",
        kb_options = "grp:alt_shift_toggle",
        numlock_by_default = true,
        follow_mouse = 1,
        mouse_refocus = false,
        touchpad = {
            natural_scroll = false,
            scroll_factor = 1.0,
            -- Touchpad scroll factor
        },
        sensitivity = 0,
        -- Pointer speed: -1.0 - 1.0, 0 means no modification.
    },
})
