-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- -----------------------------------------------------

-- General window layout and colors

-- name: "Default"

-- -----------------------------------------------------

hl.config({
    general = {
        gaps_in = 3,
        gaps_out = 5,
        border_size = 3,
        layout = "dwindle",
        resize_on_border = true,
        col = {
            active_border = color11,
            inactive_border = color8,
        },
    },
})
