[colors.primary]
background = '#201e1e'
foreground = '#f3f2f2'

[colors.cursor]
text = '#201e1e'
cursor = '#f3f2f2'

[colors.vi_mode_cursor]
text = '#201e1e'
cursor = '#e49167'

[colors.search.matches]
foreground = '#2a2827'
background = '#aacc66'

[colors.search.focused_match]
foreground = '#2a2827'
background = '#e49167'

[colors.footer_bar]
foreground = '#2a2827'
background = '#e8e5e3'

[colors.hints.start]
foreground = '#2a2827'
background = '#d6c25c'

[colors.hints.end]
foreground = '#2a2827'
background = '#d6c25c'

[colors.selection]
text = '#b6b1af'
background = '#2a2827'


[colors.normal]
black   = '#2a2827'
red     = '#fd4663'
green   = '#e49167'
yellow  = '#d6c25c'
blue    = '#aacc66'
magenta = '#ecb193'
cyan    = '#e9db96'
white   = '#f3f2f2'


[colors.bright]
black   = '#6c6865'
red     = '#fd4663'
green   = '#e49167'
yellow  = '#d6c25c'
blue    = '#aacc66'
magenta = '#ecb193'
cyan    = '#e9db96'
white   = '#f3f2f2'


[colors.dim]
black   = '#2a2827'
red     = '#fd4663'
green   = '#e49167'
yellow  = '#d6c25c'
blue    = '#aacc66'
magenta = '#ecb193'
cyan    = '#e9db96'
white   = '#f3f2f2'
