[colors.primary]
background = '#1f1f1f'
foreground = '#f3f2f2'

[colors.cursor]
text = '#1f1f1f'
cursor = '#f3f2f2'

[colors.vi_mode_cursor]
text = '#1f1f1f'
cursor = '#e46767'

[colors.search.matches]
foreground = '#292929'
background = '#cc6666'

[colors.search.focused_match]
foreground = '#292929'
background = '#e46767'

[colors.footer_bar]
foreground = '#292929'
background = '#e8e3e3'

[colors.hints.start]
foreground = '#292929'
background = '#d65c5c'

[colors.hints.end]
foreground = '#292929'
background = '#d65c5c'

[colors.selection]
text = '#b6afaf'
background = '#292929'


[colors.normal]
black   = '#292929'
red     = '#fd4663'
green   = '#e46767'
yellow  = '#d65c5c'
blue    = '#cc6666'
magenta = '#ec9393'
cyan    = '#e99696'
white   = '#f3f2f2'


[colors.bright]
black   = '#696969'
red     = '#fd4663'
green   = '#e46767'
yellow  = '#d65c5c'
blue    = '#cc6666'
magenta = '#ec9393'
cyan    = '#e99696'
white   = '#f3f2f2'


[colors.dim]
black   = '#292929'
red     = '#fd4663'
green   = '#e46767'
yellow  = '#d65c5c'
blue    = '#cc6666'
magenta = '#ec9393'
cyan    = '#e99696'
white   = '#f3f2f2'
