[colors.primary]
background = '#211c1d'
foreground = '#f3f2f2'

[colors.cursor]
text = '#211c1d'
cursor = '#f3f2f2'

[colors.vi_mode_cursor]
text = '#211c1d'
cursor = '#b3989a'

[colors.search.matches]
foreground = '#2c2626'
background = '#a3978f'

[colors.search.focused_match]
foreground = '#2c2626'
background = '#b3989a'

[colors.footer_bar]
foreground = '#2c2626'
background = '#e7e4e4'

[colors.hints.start]
foreground = '#2c2626'
background = '#a5918d'

[colors.hints.end]
foreground = '#2c2626'
background = '#a5918d'

[colors.selection]
text = '#b5b0b1'
background = '#2c2626'


[colors.normal]
black   = '#2c2626'
red     = '#d16266'
green   = '#b3989a'
yellow  = '#a5918d'
blue    = '#a3978f'
magenta = '#c9b6b7'
cyan    = '#c7bab8'
white   = '#f3f2f2'


[colors.bright]
black   = '#6e6666'
red     = '#d16266'
green   = '#b3989a'
yellow  = '#a5918d'
blue    = '#a3978f'
magenta = '#c9b6b7'
cyan    = '#c7bab8'
white   = '#f3f2f2'


[colors.dim]
black   = '#2c2626'
red     = '#d16266'
green   = '#b3989a'
yellow  = '#a5918d'
blue    = '#a3978f'
magenta = '#c9b6b7'
cyan    = '#c7bab8'
white   = '#f3f2f2'
